services:
  webapp:
    hostname: genie
    image: "ijpatricio/genie:${TAG:-latest}"
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      - PHP_OPCACHE_ENABLE=1
      - AUTORUN_ENABLED=true
    networks: [ web ]

networks: { web: { driver: bridge } }
